name: deaftv_lgdxschool_projects
description: "LG TV 데모용 Flutter 웹 앱"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LG_logo.png
    - assets/일반.png
    - assets/청각.png
    - assets/시각.png
    - assets/아동.png
    - assets/시니어.png
    - assets/일반-1.png
    - assets/청각-1.png
    - assets/시각-1.png
    - assets/아동-1.png
    - assets/시니어-1.png
    - assets/home_background.png
    - assets/settings_image.png
    - assets/가_basic.png
    - assets/가_wide.png
    - assets/가_middle.png
    

